# Generated by Django 3.2 on 2021-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='handicap',
            field=models.FloatField(default=28.0),
        ),
        migrations.DeleteModel(
            name='Handicap',
        ),
    ]
