# Generated by Django 3.2 on 2021-05-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210512_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rounds_played',
        ),
    ]
