# Generated by Django 3.2 on 2021-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_player_rounds_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole10_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole11_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole12_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole13_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole14_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole15_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole16_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole17_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole18_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole1_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole2_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole3_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole4_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole5_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole6_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole7_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole8_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='hole9_gross',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
