# Generated by Django 3.2 on 2021-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210512_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='game_type',
            field=models.CharField(choices=[('Stroke Play', 'stroke play'), ('Stableford', 'stableford'), ('Four Balls', 'four balls')], default='Stableford', max_length=15),
            preserve_default=False,
        ),
    ]
